Conditional checks added for branch protection

diff --git a/.github/workflows/Linter.yml b/.github/workflows/Linter.yml
--- a/.github/workflows/Linter.yml
+++ b/.github/workflows/Linter.yml
@@ -22,6 +22,21 @@ jobs:
           DEFAULT_BRANCH: master
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           OUTPUT_DETAILS: detailed
+      - name: Run tests and lint
+        run: |
+          npm run lint
+          npm test
+        # Add more checks as needed
+        continue-on-error: true # Continue to the next steps even if linting fails
+
+      - name: Check linting results
+        run: |
+         if [ $? -ne 0 ]; then
+          echo "Linting failed. Exiting..."
+          exit 1
+         fi   
+
+          
           
      
 
